name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --version
      - run: node --version
      - run: npm ci
        timeout-minutes: 10
      - run: npm run build --if-present
      - run: npm test

      - name: Clear npm cache
        run: npm cache clean --force
      - name: Debug environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "List of installed packages:"
          ls ./node_modules
